# Read MS Access Data and Push to Axpert

In [29]:
import csv, pyodbc
msa_drivers = [x for x in pyodbc.drivers() if 'ACCESS' in x.upper()]
print(f'MS-Access Drivers : {msa_drivers}')

MS-Access Drivers : ['Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Access Text Driver (*.txt, *.csv)']

In [62]:
import pyodbc
import pandas as pd
# set up some constants
MDB = 'D:\Python Projects\CostingModule\BILLOFMATERIAL_ACT_2023.accdb'
DRV = 'Microsoft Access Driver (*.mdb, *.accdb)'

# connect to db
con = pyodbc.connect('DRIVER={};DBQ={};'.format(DRV,MDB))
cur = con.cursor()

SQL = 'SELECT * FROM BOM_RMT;' # your query goes here
ACCESS_RM_BOM = cur.execute(SQL).fetchall()
cur.close()
con.close()
cols=['FUR_CLOR','Mat_Code','Mat_Des','Unit_CO','Rate_CO','Qty_Batch','Amt_Batch','Ev_Loss','Glass_draw',
      'Efficiency','Net_Packed','Cullet_Qty','Cullet_Rate','Cullet_Amt','Amt_Net']
Raw_BOM=pd.DataFrame(ACCESS_RM_BOM,columns=['Raw'])
Raw_BOM[cols] = Raw_BOM['Raw'].apply(lambda x: pd.Series(str(x).split(",")))
Raw_BOM.drop(columns=['Raw'],inplace=True)

In [68]:
Raw_BOM['FUR_CLOR'].str.replace("(","","'","")

C:\Users\chandan.prakash\AppData\Local\Temp\ipykernel_27244\1407922032.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  Raw_BOM['FUR_CLOR'].str.replace("(","","'","")

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
20   NaN
21   NaN
22   NaN
23   NaN
24   NaN
25   NaN
26   NaN
27   NaN
28   NaN
29   NaN
30   NaN
31   NaN
32   NaN
33   NaN
34   NaN
35   NaN
36   NaN
37   NaN
38   NaN
39   NaN
Name: FUR_CLOR, dtype: float64

In [59]:
Raw_BOM

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]

In [56]:
import pandas as pd
t1=('Furnace 2Green','RMTCALUM0001','CALUMITE', 'KGS', 0.051266599999999996, 8.0, 0.41, 0.15, 6.8, 0.7171, 4.876, 1.9239999999999995, 0.0603513, 0.116, 0.294)
pd.DataFrame(t1,columns=['Raw'])
Raw_BOM[cols] = Raw_BOM['Raw'].apply(lambda x: pd.Series(str(x).split(",")))
Raw_BOM.drop(columns=['Raw'],inplace=True)
Raw_BOM['FUR_CLOR']=Raw_BOM['FUR_CLOR'][1][2:-1]

In [57]:
Raw_BOM

,FUR_CLOR,Mat_Code,Mat_Des,Unit_CO,Rate_CO,Qty_Batch,Amt_Batch,Ev_Loss,Glass_draw,Efficiency,Net_Packed,Cullet_Qty,Cullet_Rate,Cullet_Amt,Amt_Net
0,Furnace 2Green,'RMTSOASH0001','SODA ASH','KGS',0.19404,285.0,55.301,0.15,242.25,0.7171,173.717,68.53299999999999,0.0603513,4.136,51.165)
1,Furnace 2Green,'RMTCALUM0001','CALUMITE','KGS',0.051266599999999996,8.0,0.41,0.15,6.8,0.7171,4.876,1.9239999999999995,0.0603513,0.116,0.294)
2,Furnace 2Green,'RMTSOSUL0001','SODIUM SULPHATE','KGS',0.0611342,7.0,0.428,0.15,5.95,0.7171,4.267,1.6829999999999998,0.0603513,0.102,0.326)
3,Furnace 2Green,'RMTSILSD0001','SILICA SAND','KGS',0.016093,855.0,13.76,0.15,726.75,0.7171,521.152,205.59799999999996,0.0603513,12.408,1.3520000000000003)
4,Furnace 2Green,'RMTLIMES0001','LIME STONE','KGS',0.007,235.0,1.645,0.15,199.75,0.7171,143.241,56.508999999999986,0.0603513,3.41,-1.7650000000000001)
5,Furnace 2Green,'RMTFELDS0001','FELDSPAR','KGS',0.0586124,60.0,3.517,0.15,51.0,0.7171,36.572,14.427999999999997,0.0603513,0.871,2.646)
6,Furnace 2Green,'RMTCRMOX0001','CROMIC OXIDE','KGS',0.1705396,10.0,1.705,0.15,8.5,0.7171,6.095,2.4050000000000002,0.0603513,0.145,1.56)
7,Furnace 2Green,'RMTCARBN0001','CARBON POWDER GLASS GRADE','KGS',0.2028296,1.2,0.243,0.15,1.02,0.7171,0.731,0.28900000000000003,0.0603513,0.017,0.22599999999999998)
8,Furnace 2Green,'RMTGRCUL0002','CULLET GREEN PURCHASED','KGS',0.058393,686.63,40.094,0.0,686.63,0.7171,492.382,194.248,0.0603513,11.723,28.371000000000002)
9,Furnace 2Green,'RMTSILSD0001','SILICA SAND','KGS',0.016093,1050.0,16.898,0.15,892.5,0.7739,690.706,201.79399999999998,0.0608895,12.287,4.610999999999999)
10,Furnace 2Green,'RMTSOASH0001','SODA ASH','KGS',0.19404,360.0,69.854,0.15,306.0,0.7739,236.813,69.18700000000001,0.0608895,4.213,65.641)
11,Furnace 2Green,'RMTLIMES0001','LIME STONE','KGS',0.007,285.0,1.995,0.15,242.25,0.7739,187.477,54.772999999999996,0.0608895,3.335,-1.3399999999999999)
12,Furnace 2Green,'RMTCALUM0001','CALUMITE','KGS',0.051266599999999996,50.0,2.563,0.15,42.5,0.7739,32.891,9.609000000000002,0.0608895,0.585,1.9780000000000002)
13,Furnace 2Green,'RMTFELDS0001','FELDSPAR','KGS',0.0586124,72.0,4.22,0.15,61.2,0.7739,47.363,13.837000000000003,0.0608895,0.843,3.377)
14,Furnace 2Green,'RMTSOSUL0001','SODIUM SULPHATE','KGS',0.0611342,11.0,0.672,0.15,9.35,0.7739,7.236,2.114,0.0608895,0.129,0.543)
15,Furnace 2Green,'RMTSELEN0001','SELENIUM','KGS',8.9166,0.02,0.178,0.15,0.017,0.7739,0.013,0.004000000000000002,0.0608895,0.0,0.178)
16,Furnace 2Green,'RMTCARBN0001','CARBON POWDER GLASS GRADE','KGS',0.2028296,0.0,0.0,0.15,0.0,0.7739,0.0,0.0,0.0608895,0.0,0.0)
17,Furnace 2Green,'RMTSILSD0001','SILICA SAND','KGS',0.016093,850.0,13.679,0.15,722.5,0.6633,479.234,243.26600000000002,0.0608745,14.809,-1.129999999999999)
18,Furnace 2Green,'RMTSOASH0001','SODA ASH','KGS',0.19404,290.0,56.272,0.15,246.5,0.6633,163.503,82.99700000000001,0.0608745,5.052,51.22)
19,Furnace 2Green,'RMTLIMES0001','LIME STONE','KGS',0.007,230.0,1.61,0.15,195.5,0.6633,129.675,65.82499999999999,0.0608745,4.007,-2.3969999999999994)
20,Furnace 2Green,'RMTCALUM0001','CALUMITE','KGS',0.051266599999999996,32.0,1.641,0.15,27.2,0.6633,18.042,9.157999999999998,0.0608745,0.557,1.084)
21,Furnace 2Green,'RMTFELDS0001','FELDSPAR','KGS',0.0586124,60.0,3.517,0.15,51.0,0.6633,33.828,17.171999999999997,0.0608745,1.045,2.472)
22,Furnace 2Green,'RMTSOSUL0001','SODIUM SULPHATE','KGS',0.0611342,8.0,0.489,0.15,6.8,0.6633,4.51,2.29,0.0608745,0.139,0.35)
23,Furnace 2Green,'RMTSELEN0001','SELENIUM','KGS',8.9166,0.02,0.178,0.15,0.017,0.6633,0.011,0.006000000000000002,0.0608745,0.0,0.178)
24,Furnace 2Green,'RMTCARBN0001','CARBON POWDER GLASS GRADE','KGS',0.2028296,0.0,0.0,0.15,0.0,0.6633,0.0,0.0,0.0608745,0.0,0.0)
25,Furnace 2Green,'RMTPUCUL0001','CULLET PURCHASED SHEET GLASS','KGS',0.056468000000000004,0.0,0.0,0.0,0.0,0.7739,0.0,0.0,0.0608895,0.0,0.0)
26,Furnace 2Green,'RMTFLCUL0002','CULLET FINT Generated','KGS',0.056468000000000004,400.0,22.587,0.0,400.0,0.7739,309.56,90.44,0.0608895,5.507,17.08)
27,Furnace 2Green,'RMTFLCUL0002','CULLET FINT Generated','KGS',0.056468000000000004,300.0,16.94,0.0,300.0,0.6633,198.99,101.00999999999999,0.0608745,6.149,10.791)
28,Furnace 2Green,'RMTPUCUL0001','CULLET PURCHASED SHEET GLASS','KGS',0.056468000000000004,0.0,0.0,0.0,0.0,0.6633,0.0,0.0,0.0608745,0.0,0.0)
29,Furnace 2Green,'RMTGRCUL0003','CULLET GREEN Generated','KGS',0.0582659,338.61,19.729,0.0,338.61,0.7171,242.817,95.793,0.0603513,5.781,13.948)
30,Furnace 2Green,'RMTCALUM0001','CALUMITE','KGS',0.051266599999999996,50.0,2.563,0.15,42.5,0.5095,21.654,20.846,0.0608474,1.268,1.2950000000000002)
31,Furnace 2Green,'RMTCARBN0001','CARBON POWDER GLASS GRADE','KGS',0.2028296,0.0,0.0,0.15,0.0,0.5095,0.0,0.0,0.0608474,0.0,0.0)
32,Furnace 2Green,'RMTFELDS0001','FELDSPAR','KGS',0.0586124,60.0,3.517,0.15,51.0,0.5095,25.984,25.016,0.0608474,1.522,1.9949999999999999)
33,Furnace 2Green,'RMTFLCUL0002','CULLET FINT Generated','KGS',0.056468000000000004,400.0,22.587,0.0,400.0,0.5095,203.8,196.2,0.0608474,11.938,10.649)
34,Furnace 2Green,'RMTLIMES0001','LIME STONE','KGS',0.007,285.0,1.995,0.15,242.25,0.5095,123.426,118.824,0.0608474,7.23,-5.235)
35,Furnace 2Green,'RMTPUCUL0001','CULLET PURCHASED SHEET GLASS','KGS',0.056468000000000004,0.0,0.0,0.0,0.0,0.5095,0.0,0.0,0.0608474,0.0,0.0)
36,Furnace 2Green,'RMTSELEN0001','SELENIUM','KGS',8.9166,0.02,0.178,0.15,0.017,0.5095,0.009,0.008000000000000002,0.0608474,0.0,0.178)
37,Furnace 2Green,'RMTSILSD0001','SILICA SAND','KGS',0.016093,1050.0,16.898,0.15,892.5,0.5095,454.729,437.771,0.0608474,26.637,-9.739)
38,Furnace 2Green,'RMTSOASH0001','SODA ASH','KGS',0.19404,360.0,69.854,0.15,306.0,0.5095,155.907,150.093,0.0608474,9.133,60.721000000000004)
39,Furnace 2Green,'RMTSOSUL0001','SODIUM SULPHATE','KGS',0.0611342,11.0,0.672,0.15,9.35,0.5095,4.764,4.585999999999999,0.0608474,0.279,0.393)

In [12]:
import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError
engine = sqlalchemy.create_engine("oracle+cx_oracle://majan_uat:log@192.168.0.13/?service_name=orcl", arraysize=1000)
#engine = sqlalchemy.create_engine("oracle+cx_oracle://majan29082022:log@localhost/?service_name=orcl.majanglass.com", arraysize=1000)
def readoraclequery(query):
   try:
      with engine.begin() as conn:
         df_data = pd.read_sql_query(sql=text(query), con=conn)
      return df_data
   except SQLAlchemyError as e:
      print(e)

In [8]:
import pandas as pd
from sqlalchemy import create_engine, text

engine = create_engine("oracle+cx_oracle://majan_uat:log@192.168.0.13/?service_name=orcl", arraysize=1000)
query = 'SELECT * FROM empmast'

with engine.begin() as conn:
  df = pd.read_sql_query(sql=text(query), con=conn)

In [13]:
readoraclequery('SELECT * FROM empmast')

,empmastid,cancel,sourceid,mapname,username,modifiedon,createdby,createdon,wkid,app_level,...,ara_add3,ara_city,ara_state,ara_country,emailto,emailcc,emailbcc,emailflag,egrade_bk,egrade
0,8059000000005,T,0.0,None,raj,2016-06-13 15:13:53,raj,2015-12-13 15:34:53,None,1.0,...,None,None,None,None,None,None,None,None,1.680800e+13,1.680800e+13
1,8309000000077,F,0.0,None,raj,2016-11-30 09:21:31,raj,2015-12-28 11:36:21,None,1.0,...,None,None,None,None,None,None,None,None,1.680800e+13,1.680800e+13
2,16839000000272,F,0.0,None,raj,2015-09-23 18:20:11,raj,2015-09-23 18:20:11,None,1.0,...,None,None,None,None,None,None,None,None,1.680800e+13,1.680800e+13
3,16839000000273,F,0.0,None,raj,2015-09-23 18:20:11,raj,2015-09-23 18:20:11,None,1.0,...,None,None,None,None,None,None,None,None,1.680800e+13,1.680800e+13
4,16839000000274,F,0.0,None,reception,2020-10-06 14:47:34,raj,2015-09-23 18:20:11,None,1.0,...,None,None,None,None,None,None,None,None,1.680800e+13,1.680800e+13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1187,4155000001155,F,0.0,None,reception,2023-03-16 14:50:47,reception,2023-03-14 15:13:53,None,1.0,...,كيرالا ، الهند,بالاكاد,كيرالا,الهند,hr@majanglass.com;finance@majanglass.com;,None,chandan.prakash@majanglass.com; it@majanglass....,F,NaN,1.680800e+13
1188,7699000000288,F,0.0,None,saidkhamis,2023-02-01 08:51:31,saidkhamis,2023-02-01 08:51:31,None,1.0,...,None,None,None,None,None,None,None,None,NaN,1.680800e+13
1189,7699000000292,F,0.0,None,saidkhamis,2023-02-01 08:53:33,saidkhamis,2023-02-01 08:53:33,None,1.0,...,None,None,None,None,None,None,None,None,NaN,1.680800e+13
1190,7699000000296,F,0.0,None,saidkhamis,2023-02-01 09:03:57,saidkhamis,2023-02-01 09:03:57,None,1.0,...,None,None,None,None,None,None,None,None,NaN,1.680800e+13
1191,6529000004943,F,0.0,None,fatma,2023-02-27 13:11:51,reception,2023-02-27 09:58:49,None,1.0,...,تيلانجانا ، الهند,تيلانجانا,حيدر أباد,الهند,hr@majanglass.com;finance@majanglass.com;,None,chandan.prakash@majanglass.com; it@majanglass....,F,NaN,1.680800e+13